api:
  services:
    - service: calibrate_co2_value
      variables:
        co2_ppm: int
      then:
        - scd4x.perform_forced_calibration:
            value: !lambda "return co2_ppm;"
            id: scd40

i2c:
  - id: bus_b
    sda: 26
    scl: 27
    scan: true

sensor:
  - platform: scd4x
    i2c_id: bus_b
    id: scd40
    measurement_mode: low_power_periodic    
    co2:
      name: "CO2"
      id: "co2"
    automatic_self_calibration: false

button:
    - platform: template
      name: "Calibrate CO2"
      id: calibrate_scd40
      on_press:
        - scd4x.perform_forced_calibration:
            value: 419
            id: scd40

number:
  - platform: template
    id: co2_altitude
    name: CO2 Altitude
    icon: mdi:arrow-left-right
    entity_category: config
    min_value: 0
    max_value: 3000
    initial_value: 0
    optimistic: true
    step: 1
    restore_value: true
    unit_of_measurement: m
    mode: slider
